exports.constants = {
    VALIDATION_ERROR:400 ,
    UNAUTHORIZED: 401,
    FORBIDDEN : 403,
    NOT_FOUND: 404,
    SERVER_ERROR: 500,
}
//NOW I HAVE DIFF HTTP ERROR METHODS FOR THE CLIENT AND I CAN MAKE USE OFIT IN THE ERR HANDLER